// VILLAGE — 세트 구성품 데이터 (세트마스터 시트 기반 자동 생성)
// 생성일: 2026-04-07

export interface Component {
  name: string;
  qty: number;
  note?: string;
}

// 홈페이지 제품 ID → 구성품 목록
export const productComponents: Record<number, Component[]> = {
  2: [
    { name: "셀피 스틱", qty: 1, note: "카메라" },
  ],
  5: [
    { name: "마이크*2 / 마이크 송신기", qty: 1, note: "오디오" },
  ],
  7: [
    { name: "메모리*1 / 배터리*2 / 앞캡 / 렌즈 후드", qty: 1, note: "카메라" },
  ],
  8: [
    { name: "TX *1 / RX*2 / 3.5 라인*1", qty: 1, note: "오디오" },
  ],
  9: [
    { name: "소니 BURANO 바디(풀케이지)", qty: 1, note: "카메라" },
    { name: "셔틀러 비디오 20", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1 },
    { name: "7인치 모니터", qty: 1, note: "카메라" },
    { name: "소니 CF-B 1920", qty: 1, note: "카메라" },
    { name: "소니 CF-B 960", qty: 2, note: "카메라" },
    { name: "소니 CF-B 리더기", qty: 1 },
    { name: "V마운트 배터리(SWIT)", qty: 4 },
    { name: "V마운트 배터리 충전기(SWIT)", qty: 1, note: "카메라" },
    { name: "LVM-180A", qty: 1, note: "카메라" },
    { name: "노가암, SDI 연선*3, 멀티 D탭", qty: 3, note: "카메라" },
    { name: "매트박스", qty: 1, note: "카메라" },
  ],
  10: [
    { name: "롱 SDI or HDMI", qty: 1, note: "무선" },
  ],
  11: [
    { name: "롱 SDI or HDMI", qty: 1, note: "무선" },
  ],
  13: [
    { name: "소니 BURANO 바디(풀케이지)", qty: 1, note: "카메라" },
    { name: "셔틀러 비디오 20", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "7인치 모니터", qty: 1, note: "카메라" },
    { name: "소니 CF-B 1920", qty: 1, note: "카메라" },
    { name: "소니 CF-B 960", qty: 2, note: "카메라" },
    { name: "소니 CF-B 리더기", qty: 1, note: "카메라" },
    { name: "V마운트 배터리(SWIT)", qty: 4, note: "카메라" },
    { name: "V마운트 배터리 충전기(SWIT)", qty: 1 },
    { name: "LVM-180A", qty: 1, note: "카메라" },
    { name: "매트박스", qty: 1, note: "카메라" },
    { name: "뉴클-M", qty: 1, note: "카메라" },
    { name: "테라덱 볼트 1000 XT (1:1)", qty: 1, note: "카메라" },
    { name: "노가암, 숏암, 숏암+클램프, SDI 연선*5, 멀티 D탭*2", qty: 1, note: "카메라" },
  ],
  14: [
    { name: "970더미*2 / SDI or HDMI*2 / 숏암*2", qty: 1, note: "무선" },
  ],
  16: [
    { name: "메모리*1 / 배터리*2", qty: 1, note: "카메라" },
  ],
  17: [
    { name: "캐논 R6 Mark 2 바디", qty: 1 },
    { name: "캐논 100-500 렌즈", qty: 1 },
    { name: "메모리*1 / 배터리*2 / 앞캡 / 뒷캡 / 후드", qty: 1, note: "카메라" },
  ],
  18: [
    { name: "D탭*1 / SDI or HDMI*1 / 안테나*2", qty: 1, note: "무선" },
  ],
  19: [
    { name: "D탭*2 / SDI or HDMI*2 / 안테나*6", qty: 1, note: "무선" },
  ],
  20: [
    { name: "아이솔레이터 / 브라켓 / 도브테일 / 나토레일", qty: 1, note: "그립" },
    { name: "석션컵 브라켓(롱숏) / 파워서플라이 플레이트", qty: 1, note: "그립" },
    { name: "2핀 LEMO / V프레이트 / 공기주입기", qty: 1, note: "그립" },
  ],
  21: [
    { name: "메모리*1 / 배터리*2 / 앞캡 / 후드", qty: 1, note: "카메라" },
  ],
  22: [
    { name: "헤드 / 리플렉터 / 디퓨져 / AC 라인", qty: 1, note: "조명" },
    { name: "A스탠드", qty: 1, note: "조명" },
  ],
  23: [
    { name: "패널 / 발라스터 / 연장라인 / AC라인 / 프레임대", qty: 1, note: "조명" },
    { name: "루버 / 실크1 / 실크2", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  25: [
    { name: "모터 / 컨트롤러 / 그립 / 미니로드*2 / 어댑터*1", qty: 1, note: "무선" },
    { name: "모터 배터리*2 / 컨트롤러 배터리*2", qty: 1, note: "무선" },
  ],
  26: [
    { name: "배터리그립 / 플레이트*2", qty: 1, note: "그립" },
  ],
  27: [
    { name: "헤드 / 발라스터 / 라인*2", qty: 1, note: "조명" },
    { name: "콤보스탠드", qty: 1, note: "조명" },
  ],
  28: [
    { name: "모터 / 컨트롤러 / C to D탭*1 / 로드 / 클램프 / 기어링", qty: 1, note: "무선" },
    { name: "기어링 *1", qty: 1, note: "무선" },
  ],
  30: [
    { name: "헤드 / 발라스터 / 클램프 / 라인*2", qty: 1, note: "조명" },
    { name: "소프트박스", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  31: [
    { name: "플로어 스탠드*4 / 아크릴그립*8 / 오링*4", qty: 1, note: "조명" },
    { name: "충전기*4", qty: 1, note: "조명" },
  ],
  32: [
    { name: "AC라인", qty: 1, note: "그립" },
  ],
  33: [
    { name: "플로어 스탠드*2 / 아크릴 그립*4 / 오링*2", qty: 1, note: "조명" },
    { name: "충전기*2", qty: 1, note: "조명" },
  ],
  34: [
    { name: "블림프 / 붐폴 / XLR / 데드캣", qty: 1, note: "오디오" },
  ],
  35: [
    { name: "배터리*12 / 충전기", qty: 1, note: "오디오" },
  ],
  36: [
    { name: "CooKe SP3(25/32/50/75/100)", qty: 1 },
  ],
  39: [
    { name: "배터리*8 / 충전기", qty: 1, note: "오디오" },
  ],
  40: [
    { name: "티비로직 D탭 / SDI or HDMI *1", qty: 1, note: "무선" },
  ],
  42: [
    { name: "티비로직 D탭 / SDI or HDMI *1", qty: 1, note: "무선" },
  ],
  44: [
    { name: "전용케이스", qty: 1, note: "렌즈" },
    { name: "USB 케이블", qty: 1, note: "렌즈" },
  ],
  51: [
    { name: "D탭*2 / SDI or HDMI*2 / 숏암*2", qty: 1, note: "무선" },
  ],
  53: [
    { name: "패널 / 발라스터 / 연장라인 / AC라인 / 프레임대", qty: 1, note: "조명" },
    { name: "루버 / 실크1 / 실크2", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  55: [
    { name: "C to HDMI*1 / 100볼 트라이", qty: 1, note: "그립" },
  ],
  58: [
    { name: "마이크로SD / 배터리*3  / 충전기", qty: 1, note: "카메라" },
  ],
  61: [
    { name: "캐논 오막포 바디", qty: 1, note: "카메라" },
    { name: "캐논 백사투 렌즈", qty: 1 },
    { name: "메모리*1 / 배터리*2 / 앞캡 / 뒷캡 / 후드", qty: 1 },
  ],
  64: [
    { name: "헤드 / 반도어 / 보웬스 어댑터 / D탭 / AC 라인", qty: 1, note: "조명" },
    { name: "A스탠드", qty: 1, note: "조명" },
    { name: "캐논 Mount Adapter EF-EOS R", qty: 1 },
    { name: "VILTROX Mount Adapter EF-NEX-IV", qty: 1 },
    { name: "시그마 MC-11 Canon EF-E", qty: 1 },
    { name: "NiSi PL Mount", qty: 1 },
    { name: "MOFAGE POCO PL mount", qty: 1 },
    { name: "Kipper tie REVOLVA RF-EF", qty: 1 },
    { name: "매타본즈 PL(E-PL)", qty: 1 },
    { name: "캐논 430 EX III-RT", qty: 1 },
    { name: "소니 GM 16-35mm", qty: 1 },
    { name: "소니 GM 24-70mm", qty: 1 },
    { name: "소니 GM 24-70mm 2", qty: 1 },
    { name: "소니 GM 70-200mm", qty: 1 },
    { name: "소니 GM 70-200mm 2", qty: 1 },
    { name: "소니 GM 100-400mm", qty: 1 },
    { name: "소니 G 28-135mm", qty: 1 },
    { name: "소니 G 24-105mm", qty: 1 },
    { name: "소니 90mm 매크로", qty: 1 },
    { name: "소니 단렌즈 GM 135mm", qty: 1 },
    { name: "소니 단렌즈 세트(14/24/35/50/85)", qty: 1 },
    { name: "시그마 아트 18-35mm", qty: 1 },
    { name: "시그마 아트 50-100mm", qty: 1 },
    { name: "시그마 FF 하이스피드 프라임(20/35/50/85)", qty: 1 },
    { name: "삼양 VDSLR MK2(14/24/35/50/85)", qty: 1 },
    { name: "삼양 XEEN(14/24/35/50/85)", qty: 1 },
    { name: "삼양 XEEN CF(16/24/35/50/85)", qty: 1 },
    { name: "NISI 아테나 프라임 단렌즈 세트(14/24/35/50/85)", qty: 1 },
    { name: "CooKe SP3(25/32/50/75/100)", qty: 1 },
    { name: "DZOFILM 3 Lens 세트", qty: 1 },
    { name: "삼양 100mm 매크로", qty: 1 },
    { name: "라오와 24mm f/14 Probe", qty: 1 },
    { name: "라오와 12mm T2.9 Zero-D Cine", qty: 1 },
    { name: "토키나 11-16mm F2.8 CF", qty: 1 },
    { name: "아이릭스 150mm CINE 매크로", qty: 1 },
    { name: "캐논 24-70mm", qty: 1 },
    { name: "캐논 100-400mm II", qty: 1 },
    { name: "캐논 100-500mm", qty: 1 },
    { name: "틸타 MB-T12", qty: 1 },
    { name: "틸타 MB-T16(미라지)", qty: 1 },
    { name: "틸타 MB-T15(미니)", qty: 1 },
    { name: "스몰리그 매트박스 미니", qty: 1 },
    { name: "Hollywood Blackmagic 1/2 사각", qty: 1 },
    { name: "Hollywood Blackmagic 1/4 사각", qty: 1 },
    { name: "Hollywood Blackmagic 1/8 사각", qty: 1 },
    { name: "Hollywood Blackmagic 1/4 원형", qty: 1 },
    { name: "Hollywood Blackmagic 1/8 원형", qty: 1 },
    { name: "Black Pro-Mist 1/2 사각", qty: 1 },
    { name: "Black Pro-Mist 1/4 사각", qty: 1 },
    { name: "Black Pro-Mist 1/8 사각", qty: 1 },
    { name: "Black Pro-Mist 1/2 원형", qty: 1 },
    { name: "Black Pro-Mist 1/4 원형", qty: 1 },
    { name: "Black Pro-Mist 1/8 원형", qty: 1 },
    { name: "H&Y VND-CPL 67-82mm 가변 ND", qty: 1 },
    { name: "H&Y 가변 어댑터링 37-49mm", qty: 1 },
    { name: "H&Y 가변 어댑터링 67-82mm", qty: 1 },
    { name: "NiSi PL 필터 4x5.65", qty: 1 },
    { name: "NiSi TrueColor PL 필터 4x5.65", qty: 1 },
    { name: "NiSi Allure Mist Black 1/8 사각", qty: 1 },
    { name: "NiSi IR ND 사각(0.3/0.6/0.9)", qty: 1 },
    { name: "VAXIS IRND 원형(0.3/0.6/0.9/1.2)", qty: 1 },
    { name: "틸타 미라지용 가변 ND", qty: 1 },
    { name: "V마운트 배터리", qty: 1 },
    { name: "V마운트 배터리 충전기", qty: 1 },
    { name: "970 배터리", qty: 1 },
    { name: "970 배터리 충전기", qty: 1 },
    { name: "셔틀러 비디오20 II (100볼)", qty: 1 },
    { name: "캠기어 엘리트15 (100볼)", qty: 1 },
    { name: "서튼비디오 V-15 (100볼)", qty: 1 },
    { name: "셔틀러에이스 M (75볼)", qty: 1 },
    { name: "캠기어 마크4 (75볼)", qty: 1 },
    { name: "스몰리그 (75볼)", qty: 1 },
    { name: "베이비", qty: 1 },
    { name: "하이햇", qty: 1 },
    { name: "미니 삼각대", qty: 1 },
    { name: "맨프로토(모노포드)", qty: 1 },
    { name: "시네 카트", qty: 1 },
    { name: "모션나인 카트 M1", qty: 1 },
    { name: "모션나인 C-BED", qty: 1 },
    { name: "웨건", qty: 1 },
    { name: "스탠리 카트", qty: 1 },
    { name: "5인치 모니터 BM5", qty: 1 },
    { name: "5인치 모니터 FEELWORLD 4K", qty: 1 },
    { name: "5인치 모니터 BON FM055F", qty: 1 },
    { name: "티비로직 VFM-055A", qty: 1 },
    { name: "포트키 7인치", qty: 1 },
    { name: "스몰HD INDIE7", qty: 1 },
    { name: "티비로직 LVM-075A", qty: 1 },
    { name: "LVM-173W", qty: 1 },
    { name: "LVM-173W-3G", qty: 1 },
    { name: "LVM-182W-A", qty: 1 },
    { name: "BON 17인치", qty: 1 },
    { name: "SEETEC 17인치", qty: 1 },
    { name: "로닌 링그립", qty: 1 },
    { name: "로닌 듀얼그립", qty: 1 },
    { name: "소니 ECM-XM1", qty: 1 },
    { name: "소니 XLR-K3M", qty: 1 },
    { name: "소니 XLR-H1", qty: 1 },
    { name: "붐마이크 거치대(홀더)", qty: 1 },
    { name: "TAKSTAR CM-63", qty: 1 },
    { name: "로데 비디오마이크 프로", qty: 1 },
    { name: "헤드폰 ATH-M20X", qty: 1 },
    { name: "헤드폰 ATH-M50X", qty: 1 },
    { name: "파보튜브 II 30X", qty: 1 },
    { name: "파보튜브 II 30XR", qty: 1 },
    { name: "아마란 spotlight SE", qty: 1 },
    { name: "어퓨쳐 spotlight", qty: 1 },
    { name: "아마란 라이트돔 미니 SE", qty: 1 },
    { name: "어퓨쳐 라이트돔 미니 SE", qty: 1 },
    { name: "라이트돔 II", qty: 1 },
    { name: "라이트돔 GODEX QR-P120", qty: 1 },
    { name: "라이트돔 GODEX QR-P90", qty: 1 },
    { name: "젬볼", qty: 1 },
    { name: "젬볼 90", qty: 1 },
    { name: "넉자 그리드", qty: 1 },
    { name: "석자 그리드", qty: 1 },
    { name: "넉자 플로피", qty: 1 },
    { name: "석자 플로피", qty: 1 },
    { name: "스크림 세트", qty: 1 },
    { name: "F10 프레넬+반도어(600용)", qty: 1 },
    { name: "2X 프레넬 렌즈(300용)", qty: 1 },
    { name: "300용 반도어", qty: 1 },
    { name: "반도어 에그크레이트(파보튜브 30용)", qty: 1 },
    { name: "KUPO 콤보 스탠드", qty: 1 },
    { name: "베이비 콤보 스탠드", qty: 1 },
    { name: "미니 콤보스탠드(어벤져 A1010CS)", qty: 1 },
    { name: "C Boom AVENGER D600", qty: 1 },
    { name: "C스탠드", qty: 1 },
    { name: "A스탠드", qty: 1 },
    { name: "오토폴", qty: 1 },
    { name: "포그 머신", qty: 1 },
    { name: "헤이져 머신", qty: 1 },
    { name: "턴테이블(T360-60)", qty: 1 },
    { name: "발전기 툴콘 TG-1800K", qty: 1 },
    { name: "발전기 툴콘 TG-1000K", qty: 1 },
    { name: "애플박스 풀세트", qty: 1 },
    { name: "F10 프레넬+반도어(600용)", qty: 1 },
    { name: "Nisi PL Mount", qty: 1 },
    { name: "소니 FX3 바디(케이지)", qty: 1 },
    { name: "소니 FX6 바디(케이지)", qty: 1 },
    { name: "소니 FX9 바디(케이지)", qty: 1 },
    { name: "소니 A7S3 바디(케이지)", qty: 1 },
    { name: "레드 코모도 6K 바디(케이지)", qty: 1 },
    { name: "BMPCC 6K", qty: 1 },
    { name: "BMPCC 6K PRO", qty: 1 },
    { name: "고프로 10", qty: 1 },
    { name: "고프로 11", qty: 1 },
    { name: "고프로 12", qty: 1 },
    { name: "업링 72-86mm", qty: 1 },
    { name: "업링 77-86mm", qty: 1 },
    { name: "업링 82-86mm", qty: 1 },
    { name: "업링 72-82mm", qty: 1 },
    { name: "다운링 82-72mm", qty: 1 },
    { name: "캠코더 배터리 NP-FV (전체)", qty: 1 },
    { name: "캠코더 충전기 NP-FV100", qty: 1 },
    { name: "오막포 배터리 (전체)", qty: 1 },
    { name: "오막포 충전기", qty: 1 },
    { name: "970 배터리 (전체)", qty: 1 },
    { name: "970 충전기 (전체)", qty: 1 },
    { name: "FX9/6 배터리 (전체)", qty: 1 },
    { name: "FX9/6 충전기", qty: 1 },
    { name: "NP-FZ100", qty: 1 },
    { name: "NP-FZ100 충전기", qty: 1 },
    { name: "코모도 배터리", qty: 1 },
    { name: "나이트코어 2구 충전기", qty: 1 },
    { name: "소니 CFA/SD 리더기", qty: 1 },
    { name: "FX9 XQD/SD 리더기", qty: 1 },
    { name: "소니 XQD 리더기", qty: 1 },
    { name: "FX9 XQD/SD/USB 리더기 비정품", qty: 1 },
    { name: "코모도 CFast 2.0 리더기", qty: 1 },
    { name: "소니 CF-A 160", qty: 1 },
    { name: "소니 CF-A 128", qty: 1 },
    { name: "소니 CF-A 80", qty: 1 },
    { name: "소니 XQD 120", qty: 1 },
    { name: "소니 XQD 240", qty: 1 },
    { name: "AV PRO CF 256", qty: 1 },
    { name: "AV PRO CF 512", qty: 1 },
    { name: "RED Pro CFast 512GB", qty: 1 },
    { name: "삼성 SSD T5", qty: 1 },
    { name: "프롬프터", qty: 1 },
    { name: "마스 400S (RX)", qty: 1 },
    { name: "마스 400S (TX)", qty: 1 },
    { name: "마스 400S 프로 (RX)", qty: 1 },
    { name: "마스 400S 프로 (TX)", qty: 1 },
    { name: "마스 4K (RX)", qty: 1 },
    { name: "마스 4K (TX)", qty: 1 },
    { name: "VAXIS 아톰 500 SDI (RX)", qty: 1 },
    { name: "VAXIS 아톰 500 SDI (TX)", qty: 1 },
    { name: "DJI 트렌스미션 (RX)", qty: 1 },
    { name: "DJI 트렌스미션 (TX)", qty: 1 },
    { name: "파이로S 4K (RX)", qty: 1 },
    { name: "파이로S 4K (TX)", qty: 1 },
    { name: "파이로7", qty: 1 },
    { name: "테라덱 볼트 1000 XT (1:1)", qty: 1 },
    { name: "테라덱 볼트 500 LT (1:1)", qty: 1 },
    { name: "틸타 뉴클리어스-M 모터", qty: 1 },
    { name: "틸타 뉴클리어스-M 컨트롤러", qty: 1 },
    { name: "틸타 뉴클리어스-N 모터", qty: 1 },
    { name: "틸타 뉴클리어스-N 컨트롤러", qty: 1 },
    { name: "틸타 뉴클리어스-N2 모터", qty: 1 },
    { name: "틸타 뉴클리어스-N2 컨트롤러", qty: 1 },
    { name: "틸타 뉴클리어스-N2 컨트롤 핸들", qty: 1 },
    { name: "모토로라 무전기 2개 SET", qty: 1 },
    { name: "로닌 RS2 프로 콤보", qty: 1 },
    { name: "로닌 듀얼 그립 Set(스몰리그)", qty: 1 },
    { name: "로닌 듀얼 그립 개별(RONIN)", qty: 1 },
    { name: "크레인 3S", qty: 1 },
    { name: "지윤 크레인 링그립", qty: 1 },
    { name: "지윤 크레인 듀얼그립", qty: 1 },
    { name: "슬라이더", qty: 1 },
    { name: "젠하이져 MKH-416P", qty: 1 },
    { name: "소니 UWP-D21 세트(송수신기)", qty: 1 },
    { name: "홀리랜드 솔리드컴 C1 Pro 4개 세트", qty: 1 },
    { name: "이어폰", qty: 1 },
    { name: "어퓨쳐 600X 프로", qty: 1 },
    { name: "어퓨쳐 600C 프로", qty: 1 },
    { name: "어퓨쳐 아마란 300C", qty: 1 },
    { name: "어퓨쳐 아마란 F21C", qty: 1 },
    { name: "어퓨쳐 아마란 F22C", qty: 1 },
    { name: "NANLUX Evoke 1200B", qty: 1 },
    { name: "어퓨쳐 B7C 1구", qty: 1 },
    { name: "어퓨쳐 MC4 트래블 KIT", qty: 1 },
    { name: "아마란 PT4C", qty: 1 },
    { name: "파보튜브 II 6C", qty: 1 },
    { name: "파보튜브 C그립", qty: 1 },
    { name: "파보튜브 플로어 스탠드", qty: 1 },
    { name: "조명 싱글(초록)", qty: 1 },
    { name: "조명 더블(빨간색)", qty: 1 },
    { name: "F10 프레넬 렌즈(600용)", qty: 1 },
    { name: "F10 반도어(600용)", qty: 1 },
    { name: "반도어 크리에이트", qty: 1 },
    { name: "그립암", qty: 1 },
    { name: "그립헤드", qty: 1 },
    { name: "발전기 에코플로우 델타 맥스2", qty: 1 },
    { name: "발전기 에코플로우 델타", qty: 1 },
    { name: "발전기 에코플로우 델타 맥스 에스트라", qty: 1 },
    { name: "애플박스 풀세트(A/B/C/D)", qty: 1 },
    { name: "애플박스 풀 단품", qty: 1 },
    { name: "애플박스 하프 단품", qty: 1 },
    { name: "애플박스 쿼터 단품", qty: 1 },
    { name: "애플박스 팬케익 단품", qty: 1 },
    { name: "매직암(소)", qty: 1 },
    { name: "매직암(중)", qty: 1 },
    { name: "노가암", qty: 1 },
    { name: "슈퍼클램프", qty: 1 },
    { name: "매슬리니", qty: 1 },
    { name: "탑 클램프 MB-55", qty: 1 },
    { name: "탑 클램프 M11-095", qty: 1 },
    { name: "뽕", qty: 1 },
    { name: "깍두기", qty: 1 },
    { name: "TV로직 D탭 케이블", qty: 1 },
    { name: "SDI 두꺼운 라인", qty: 1 },
    { name: "SDI 연선", qty: 1 },
    { name: "HDMI 대", qty: 1 },
    { name: "HDMI 중", qty: 1 },
    { name: "HDMI V2.0 케이블", qty: 1 },
    { name: "리더기 CtoC 케이블", qty: 1 },
    { name: "소니 GM 24-70mm II", qty: 1 },
    { name: "소니 GM 70-200mm II", qty: 1 },
    { name: "블랙매직 멀티뷰", qty: 2 },
  ],
  65: [
    { name: "AC라인", qty: 1, note: "그립" },
  ],
  66: [
    { name: "헤드 / 발라스터 / 클램프 / 라인*2", qty: 1, note: "조명" },
    { name: "소프트박스", qty: 1, note: "조명" },
    { name: "A스탠드", qty: 1, note: "조명" },
  ],
  67: [
    { name: "AC라인", qty: 1, note: "조명" },
    { name: "A스탠드", qty: 1, note: "조명" },
  ],
  68: [
    { name: "마이크로SD / 배터리*3  / 충전기", qty: 1, note: "카메라" },
  ],
  70: [
    { name: "소니 A7S3 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 2, note: "카메라" },
    { name: "NP-FZ100", qty: 3, note: "카메라" },
    { name: "NP-FZ100 충전기", qty: 1, note: "카메라" },
  ],
  71: [
    { name: "소니 FX3 바디(케이지)", qty: 1, note: "할인 품목" },
    { name: "소니 CF-A 160", qty: 2, note: "할인 품목" },
    { name: "소니 CF-A 리더기", qty: 1, note: "할인 품목" },
    { name: "NP-FZ100", qty: 3, note: "할인 품목" },
    { name: "NP-FZ100 충전기", qty: 1 },
  ],
  73: [
    { name: "소니 FX6 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 1, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
  ],
  74: [
    { name: "헤드 / 발라스터 / 라인*2", qty: 1 },
    { name: "노바용 소프트박스", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  75: [
    { name: "비디오 헤드 / 75볼 트라이*2 / 970배터리*2", qty: 1, note: "그립" },
  ],
  80: [
    { name: "헤드 / 발라스터 / 클램프 / 라인*2", qty: 1, note: "조명" },
    { name: "소프트박스", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  81: [
    { name: "헤드 / 발라스터 / 클램프 / 라인*2", qty: 1, note: "조명" },
    { name: "소프트박스", qty: 1, note: "조명" },
    { name: "C스탠드", qty: 1, note: "조명" },
  ],
  82: [
    { name: "베이비 콤보*2", qty: 1, note: "그립" },
  ],
  83: [
    { name: "970더미*1 / SDI or HDMI*1 / 숏암*1", qty: 1, note: "무선" },
  ],
  84: [
    { name: "레드 코모도 6K 바디(케이지)", qty: 1, note: "할인 품목" },
    { name: "100볼 트라이", qty: 1, note: "할인 품목" },
    { name: "베이비", qty: 1, note: "할인 품목" },
    { name: "하이햇", qty: 1, note: "할인 품목" },
    { name: "7인치 모니터", qty: 1, note: "할인 품목" },
    { name: "AV PRO CF 512", qty: 2, note: "할인 품목" },
    { name: "AV PRO CF 256", qty: 1 },
    { name: "AV PRO CF 리더기", qty: 1 },
    { name: "V마운트 배터리", qty: 4, note: "할인 품목" },
    { name: "V마운트 배터리 충전기", qty: 1 },
    { name: "LVM-170A", qty: 1, note: "할인 품목" },
  ],
  85: [
    { name: "배터리그립 / 플레이트*2", qty: 1, note: "그립" },
  ],
  89: [
    { name: "무전기*2 / 이어폰*2 / 충전기*2", qty: 1, note: "오디오" },
  ],
  92: [
    { name: "16-35 / 24-70 / 70-200", qty: 1, note: "렌즈" },
  ],
  95: [
    { name: "소니 FX9 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 XQD 240", qty: 1, note: "카메라" },
    { name: "소니 XQD 120", qty: 2, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
  ],
  100: [
    { name: "아이리스 / 고보 *3", qty: 1, note: "조명" },
  ],
  101: [
    { name: "17인치 모니터", qty: 1, note: "무선" },
    { name: "무선 송수신기", qty: 1, note: "무선" },
    { name: "뉴클-M", qty: 1, note: "무선" },
  ],
  102: [
    { name: "7인치 모니터", qty: 1, note: "무선" },
    { name: "무선 송수신기", qty: 1, note: "무선" },
    { name: "뉴클-M", qty: 1, note: "무선" },
  ],
  103: [
    { name: "충전기", qty: 1, note: "오디오" },
  ],
  105: [
    { name: "핀마이크(솜, 클립) / 3.5 라인*1 / XLR 라인*1", qty: 1, note: "오디오" },
  ],
  109: [
    { name: "본체 / 케이블*3", qty: 1, note: "조명" },
  ],
  110: [
    { name: "이어셋*5", qty: 1, note: "오디오" },
  ],
  111: [
    { name: "배터리그립 / 플레이트*2", qty: 2, note: "그립" },
  ],
  112: [
    { name: "소니 A7S3 바디(케이지)", qty: 1, note: "카메라" },
    { name: "75볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "5인치 모니터", qty: 1, note: "카메라" },
    { name: "매트박스", qty: 1 },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 1, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
    { name: "V마운트 배터리 충전기", qty: 1, note: "카메라" },
    { name: "NP-FZ100", qty: 3 },
    { name: "NP-FZ100 충전기", qty: 1 },
    { name: "매직암, HDMI 라인, 970더미, C to C", qty: 1 },
  ],
  119: [
    { name: "블림프 / 붐폴 / XLR / 데드캣", qty: 1, note: "오디오" },
  ],
  120: [
    { name: "32기가 메모리, 전용 가방", qty: 1, note: "오디오" },
  ],
  121: [
    { name: "32기가 메모리", qty: 1, note: "오디오" },
  ],
  123: [
    { name: "파워박스 / 듀얼그립 or 링그립", qty: 1, note: "그립" },
  ],
  125: [
    { name: "매직캠*1 / 슈퍼클램프*1", qty: 1, note: "그립" },
  ],
  127: [
    { name: "D탭*2 / SDI or HDMI*2 / 숏암*2", qty: 1, note: "무선" },
  ],
  128: [
    { name: "D탭*2 / SDI or HDMI*2  / 숏암*2", qty: 1, note: "무선" },
  ],
  129: [
    { name: "D탭*3 / 안테나*12 / SDI*3 / 숏암*3", qty: 1, note: "무선" },
  ],
  130: [
    { name: "D탭*2 / SDI*2 / 안테나*2 / 숏암*2", qty: 1, note: "무선" },
  ],
  131: [
    { name: "970더미*2 / SDI or HDMI*2 / 숏암*2", qty: 1, note: "무선" },
  ],
  134: [
    { name: "D탭 / SDI or HDMI *1", qty: 1, note: "무선" },
  ],
  135: [
    { name: "롱 SDI or HDMI", qty: 1, note: "무선" },
  ],
  137: [
    { name: "모터 / 컨트롤러 / D탭 / 배터리*4 / 충전기", qty: 1, note: "무선" },
  ],
  138: [
    { name: "패널 / 발라스터 / 연장라인 / AC라인", qty: 1, note: "조명" },
    { name: "루버 / 실크", qty: 1, note: "조명" },
    { name: "A스탠드", qty: 1, note: "조명" },
  ],
  140: [
    { name: "조명기 / 파우치", qty: 1, note: "조명" },
  ],
  142: [
    { name: "충전 케이스 / 케이블", qty: 1, note: "조명" },
  ],
  143: [
    { name: "실리콘 디퓨전*2 / 볼헤드*2 / 충전케이스 / 케이블", qty: 1, note: "조명" },
  ],
  145: [
    { name: "그립헤드, 그립암", qty: 1, note: "조명" },
  ],
  147: [
    { name: "고보 / 실크 / 싱글 / 더블 / 우드락", qty: 1, note: "조명" },
  ],
  151: [
    { name: "18-35 / 50-100", qty: 1, note: "렌즈" },
  ],
  155: [
    { name: "67 / 72 / 77 / 82 업링", qty: 1, note: "렌즈" },
  ],
  161: [
    { name: "소니 FE 28-135mm 렌즈", qty: 1 },
    { name: "소니 A7S3 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 2, note: "카메라" },
    { name: "NP-FZ100", qty: 3, note: "카메라" },
    { name: "NP-FZ100 충전기", qty: 1, note: "카메라" },
  ],
  162: [
    { name: "소니 GM 24-70mm II 렌즈", qty: 1 },
    { name: "소니 A7S3 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 2, note: "카메라" },
    { name: "NP-FZ100", qty: 3, note: "카메라" },
    { name: "NP-FZ100 충전기", qty: 1, note: "카메라" },
  ],
  163: [
    { name: "소니 FE 28-135mm 렌즈", qty: 1 },
    { name: "소니 FX3 바디(케이지)", qty: 1, note: "할인 품목" },
    { name: "소니 CF-A 160", qty: 2, note: "할인 품목" },
    { name: "소니 CF-A 리더기", qty: 1, note: "할인 품목" },
    { name: "NP-FZ100", qty: 3, note: "할인 품목" },
    { name: "NP-FZ100 충전기", qty: 1 },
  ],
  164: [
    { name: "소니 GM 24-70mm II 렌즈", qty: 1 },
    { name: "소니 FX3 바디(케이지)", qty: 1, note: "할인 품목" },
    { name: "소니 CF-A 160", qty: 2, note: "할인 품목" },
    { name: "소니 CF-A 리더기", qty: 1, note: "할인 품목" },
    { name: "NP-FZ100", qty: 3, note: "할인 품목" },
    { name: "NP-FZ100 충전기", qty: 1 },
  ],
  165: [
    { name: "소니 FE 28-135mm 렌즈", qty: 1 },
    { name: "소니 FX6 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 1, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
  ],
  166: [
    { name: "소니 FE 28-135mm 렌즈", qty: 1 },
    { name: "소니 FX9 바디(케이지)", qty: 1, note: "카메라" },
    { name: "소니 XQD 240", qty: 1, note: "카메라" },
    { name: "소니 XQD 120", qty: 2, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
  ],
  167: [
    { name: "본체 / 마이크로SD / 여분 배터리*1", qty: 1, note: "카메라" },
  ],
  168: [
    { name: "메모리 *1 / 배터리*2 / 바디캡", qty: 1, note: "카메라" },
  ],
  169: [
    { name: "메모리 *1 / 배터리*2 / 바디캡", qty: 1, note: "카메라" },
  ],
  170: [
    { name: "소니 FX3 바디(케이지)", qty: 1, note: "카메라" },
    { name: "75볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "5인치 모니터", qty: 1, note: "카메라" },
    { name: "매트박스", qty: 2, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 2, note: "카메라" },
    { name: "V마운트 배터리", qty: 4, note: "카메라" },
    { name: "V마운트 배터리 충전기", qty: 1, note: "카메라" },
    { name: "NP-FZ100", qty: 3 },
    { name: "NP-FZ100 충전기", qty: 1 },
    { name: "매직암, HDMI 라인, 970더미, C to C", qty: 1 },
  ],
  179: [
    { name: "소니 FX6 바디(케이지)", qty: 1, note: "카메라" },
    { name: "100볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "7인치 모니터", qty: 1, note: "카메라" },
    { name: "매트박스", qty: 1, note: "카메라" },
    { name: "소니 CF-A 160", qty: 2, note: "카메라" },
    { name: "소니 CF-A 리더기", qty: 1, note: "카메라" },
    { name: "V마운트 배터리", qty: 4, note: "카메라" },
    { name: "V마운트 배터리 충전기", qty: 1 },
    { name: "LVM-170A", qty: 1, note: "카메라" },
    { name: "SDI 롱라인, SDI 라인, 노가암", qty: 1 },
  ],
  180: [
    { name: "모터 / 컨트롤러 / C to D탭*1 / 로드 / 클램프 / 기어링", qty: 1, note: "무선" },
    { name: "기어링 *1", qty: 1, note: "무선" },
  ],
  181: [
    { name: "AC라인", qty: 1, note: "무선" },
  ],
  182: [
    { name: "소니 FX9 바디(케이지)", qty: 1, note: "카메라" },
    { name: "100볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1 },
    { name: "7인치 모니터", qty: 1, note: "카메라" },
    { name: "매트박스", qty: 1 },
    { name: "소니 XQD 256", qty: 1, note: "카메라" },
    { name: "소니 XQD 128", qty: 2 },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
    { name: "V마운트 배터리 충전기", qty: 1 },
    { name: "LVM-170A", qty: 2, note: "카메라" },
    { name: "SDI 롱라인, SDI 라인, 노가암", qty: 4, note: "카메라" },
  ],
  183: [
    { name: "BMPCC 6K PRO 바디(케이지)", qty: 1, note: "카메라" },
    { name: "75볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "5인치 모니터", qty: 1, note: "카메라" },
    { name: "삼성 T5 1TB SSD", qty: 2, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
    { name: "970 더미, HDMI 라인, 멀티 D탭", qty: 1, note: "카메라" },
  ],
  186: [
    { name: "BMPCC 6K 바디(케이지)", qty: 1, note: "카메라" },
    { name: "75볼 트라이", qty: 1, note: "카메라" },
    { name: "베이비", qty: 1, note: "카메라" },
    { name: "하이햇", qty: 1, note: "카메라" },
    { name: "5인치 모니터", qty: 1, note: "카메라" },
    { name: "삼성 T5 1TB SSD", qty: 2, note: "카메라" },
    { name: "V마운트 배터리", qty: 2, note: "카메라" },
    { name: "970 더미, HDMI 라인, 멀티 D탭", qty: 1, note: "카메라" },
  ],
};
